name: Android CI

on: [workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          gradle-version: '7.5.1'
      - uses: gradle/gradle-build-action@v2
      - name: Lint Android
        run: ./gradlew wrapper --gradle-version=6.8.3 && ./gradlew lint
        #run: sudo curl -s "https://get.sdkman.io" | bash && sudo source "/home/`whoami`/.sdkman/bin/sdkman-init.sh" && sudo sdk use gradle 7.5.1 && ./gradlew lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          gradle-version: '7.5.1'
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew wrapper --gradle-version=6.8.3 && ./gradlew app:assemble
