name: Android CI

on: [workflow_dispatch]

#https://www.youtube.com/watch?v=8p3gdc1jqw8
#https://gradle.org/releases/
#https://mkyong.com/java/list-of-java-class-file-major-version-numbers/
#https://docs.gradle.org/6.0/release-notes.html


jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 13 #17
      - uses: gradle/gradle-build-action@v2
      - name: Lint Android
        run: ./gradlew wrapper --gradle-version=6.8.3 && ./gradlew lint
        #run: sudo curl -s "https://get.sdkman.io" | bash && sudo source "/home/`whoami`/.sdkman/bin/sdkman-init.sh" && sudo sdk use gradle 7.5.1 && ./gradlew lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew wrapper --gradle-version=6.8.3 && ./gradlew app:assemble
